// Visualizador WebGL equiretangular local. Não envia a imagem nem requer biblioteca externa.
const VS=`attribute vec2 a;varying vec2 v;void main(){v=(a+1.0)*0.5;gl_Position=vec4(a,0.0,1.0);}`;
const FS=`precision highp float;varying vec2 v;uniform sampler2D tex;uniform vec2 rot;uniform float fov;uniform vec2 aspect;const float PI=3.141592653589793;void main(){vec2 p=(v*2.0-1.0)*aspect*tan(fov*0.5);vec3 d=normalize(vec3(p.x,-p.y,1.0));float cy=cos(rot.x),sy=sin(rot.x),cp=cos(rot.y),sp=sin(rot.y);d=mat3(cy,0.0,-sy,0.0,1.0,0.0,sy,0.0,cy)*d;d=mat3(1.0,0.0,0.0,0.0,cp,sp,0.0,-sp,cp)*d;float lon=atan(d.x,d.z);float lat=asin(clamp(d.y,-1.0,1.0));vec2 uv=vec2(fract(0.5+lon/(2.0*PI)),0.5-lat/PI);gl_FragColor=texture2D(tex,uv);}`;
function shader(gl,type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
export class PanoramaViewer{constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl",{antialias:true,alpha:false});if(!this.gl)throw new Error("WebGL indisponível");this.yaw=0;this.pitch=0;this.fov=Math.PI/2;this.drag=null;this._init();this._events();this.resize();}
 _init(){const g=this.gl,p=g.createProgram();g.attachShader(p,shader(g,g.VERTEX_SHADER,VS));g.attachShader(p,shader(g,g.FRAGMENT_SHADER,FS));g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(p));g.useProgram(p);const b=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,b);g.bufferData(g.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),g.STATIC_DRAW);const a=g.getAttribLocation(p,"a");g.enableVertexAttribArray(a);g.vertexAttribPointer(a,2,g.FLOAT,false,0,0);this.program=p;this.texture=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.texture);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.REPEAT);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR);this.u={rot:g.getUniformLocation(p,"rot"),fov:g.getUniformLocation(p,"fov"),aspect:g.getUniformLocation(p,"aspect")};}
 _events(){this.down=e=>{this.drag=[e.clientX,e.clientY,this.yaw,this.pitch];this.canvas.setPointerCapture?.(e.pointerId);};this.move=e=>{if(!this.drag)return;this.yaw=this.drag[2]-(e.clientX-this.drag[0])*0.005;this.pitch=Math.max(-1.5,Math.min(1.5,this.drag[3]-(e.clientY-this.drag[1])*0.005));this.render();};this.up=()=>{this.drag=null;};this.wheel=e=>{e.preventDefault();this.fov=Math.max(0.35,Math.min(2.4,this.fov+Math.sign(e.deltaY)*0.08));this.render();};this.canvas.addEventListener("pointerdown",this.down);this.canvas.addEventListener("pointermove",this.move);this.canvas.addEventListener("pointerup",this.up);this.canvas.addEventListener("wheel",this.wheel,{passive:false});}
 async load(url,{crossOrigin=null}={}){const img=new Image();if(crossOrigin)img.crossOrigin=crossOrigin;await new Promise((ok,fail)=>{img.onload=ok;img.onerror=()=>fail(new Error(`Falha ao carregar panorama local: ${url}`));img.src=url;});const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.texture);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,false);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,img);this.render();return{width:img.naturalWidth,height:img.naturalHeight};}
 setView({heading=0,pitch=0,fovDeg=90}){this.yaw=heading*Math.PI/180;this.pitch=pitch*Math.PI/180;this.fov=fovDeg*Math.PI/180;this.render();}
 resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(this.canvas.clientWidth*dpr)),h=Math.max(1,Math.round(this.canvas.clientHeight*dpr));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}this.gl.viewport(0,0,w,h);this.render();}
 render(){const g=this.gl;if(!g)return;g.useProgram(this.program);g.uniform2f(this.u.rot,this.yaw,this.pitch);g.uniform1f(this.u.fov,this.fov);const ar=this.canvas.width/this.canvas.height;g.uniform2f(this.u.aspect,ar,1);g.drawArrays(g.TRIANGLES,0,6);}
 dispose(){this.canvas.removeEventListener("pointerdown",this.down);this.canvas.removeEventListener("pointermove",this.move);this.canvas.removeEventListener("pointerup",this.up);this.canvas.removeEventListener("wheel",this.wheel);this.gl.deleteTexture(this.texture);this.gl.deleteProgram(this.program);this.gl=null;}}
