export const clamp01=t=>Math.max(0,Math.min(1,t));
export const lerp=(a,b,t)=>a+(b-a)*t;
export function lerpArray(a,b,t){if(a.length!==b.length)throw new Error("vetores incompatíveis");return a.map((v,i)=>lerp(v,b[i],t));}
export function hermite(p0,p1,m0,m1,t){const t2=t*t,t3=t2*t;return (2*t3-3*t2+1)*p0+(t3-2*t2+t)*m0+(-2*t3+3*t2)*p1+(t3-t2)*m1;}
export function bezier(p0,c0,c1,p1,t){const u=1-t;return u*u*u*p0+3*u*u*t*c0+3*u*t*t*c1+t*t*t*p1;}
export function normalizeQuat(q){const n=Math.hypot(...q);if(!n)return[0,0,0,1];return q.map(v=>v/n);}
export function slerp(a,b,t){a=normalizeQuat(a);b=normalizeQuat(b);let dot=a.reduce((s,v,i)=>s+v*b[i],0);if(dot<0){b=b.map(v=>-v);dot=-dot;}if(dot>0.9995)return normalizeQuat(lerpArray(a,b,t));const theta0=Math.acos(Math.max(-1,Math.min(1,dot)));const theta=theta0*t;const sin0=Math.sin(theta0);const s0=Math.cos(theta)-dot*Math.sin(theta)/sin0;const s1=Math.sin(theta)/sin0;return a.map((v,i)=>s0*v+s1*b[i]);}
export function geodesic([lon1,lat1,alt1=0],[lon2,lat2,alt2=0],t){const r=Math.PI/180,p1=lat1*r,p2=lat2*r,l1=lon1*r,l2=lon2*r;const x1=Math.cos(p1)*Math.cos(l1),y1=Math.cos(p1)*Math.sin(l1),z1=Math.sin(p1);const x2=Math.cos(p2)*Math.cos(l2),y2=Math.cos(p2)*Math.sin(l2),z2=Math.sin(p2);let dot=Math.max(-1,Math.min(1,x1*x2+y1*y2+z1*z2));const omega=Math.acos(dot);let x,y,z;if(omega<1e-9){x=lerp(x1,x2,t);y=lerp(y1,y2,t);z=lerp(z1,z2,t);}else{const so=Math.sin(omega),a=Math.sin((1-t)*omega)/so,b=Math.sin(t*omega)/so;x=a*x1+b*x2;y=a*y1+b*y2;z=a*z1+b*z2;}const lon=Math.atan2(y,x)/r,lat=Math.atan2(z,Math.hypot(x,y))/r;return[lon,lat,lerp(alt1,alt2,t)];}
export function logAltitude(a,b,t){const sign=a<0||b<0?null:1;if(!sign)return lerp(a,b,t);return Math.expm1(lerp(Math.log1p(a),Math.log1p(b),t));}
export function interpolateValue(k0,k1,frame,valueType){if(k1.frame===k0.frame)return k1.value;const t=clamp01((frame-k0.frame)/(k1.frame-k0.frame));switch(k0.interpolation){case"hold":return k0.value;case"slerp":return slerp(k0.value,k1.value,t);case"geodesic":return geodesic(k0.value,k1.value,t);case"log_altitude":return logAltitude(k0.value,k1.value,t);case"hermite":return valueType==="number"?hermite(k0.value,k1.value,k0.out_tangent||0,k1.in_tangent||0,t):k0.value.map((v,i)=>hermite(v,k1.value[i],k0.out_tangent?.[i]||0,k1.in_tangent?.[i]||0,t));case"bezier":return valueType==="number"?bezier(k0.value,k0.out_tangent??k0.value,k1.in_tangent??k1.value,k1.value,t):k0.value.map((v,i)=>bezier(v,k0.out_tangent?.[i]??v,k1.in_tangent?.[i]??k1.value[i],k1.value[i],t));default:return valueType==="number"?lerp(k0.value,k1.value,t):Array.isArray(k0.value)?lerpArray(k0.value,k1.value,t):t<.5?k0.value:k1.value;}}
